server:
  port: ${SERVER_PORT:8082}
  servlet:
    contextPath: ${CONTEXT_PATH:/api}
spring:
  spring:
    zipkin:
      base-url: http://localhost:9411
    sleuth:
      sampler:
        probability: 1.0
  datasource:
    password: ${DATABASE_PASSWORD}
    username: ${DATABASE_USERNAME}
    url: jdbc:postgresql://${DATABASE_URL}:${DATABASE_PORT}/${DATABASE_NAME:OrderService}
    driver-class-name: org.postgresql.Driver
  profiles:
    active: local

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc.batch_size: 30
        order_inserts: true
        jdbc.time_zone: UTC
        dialect: org.hibernate.dialect.PostgreSQLDialect
        types.print.banner: false
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: notificationTopic
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            type:
              mapping: event:com.Peaqock.order_service.Events.OrderPlacedEvent
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

#Resilinece4j Properties
resilience4j:
  circuitbreaker:
    instances:
      inventory:
        registerHealthIndicator: true
        event-consumer-buffer-size: 10
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
  timelimiter:
    instances:
      inventory:
        timeoutDuration: 3s #if 3 s passed without a result, exception  is threw
  retry:
    instances:
      inventory:
        maxAttempts: 3 #number of retry to access to the service
        waitDuration: 5s
