SERVER_PORT: 8082
CONTEXT_PATH: /api

############# DATABASE INFO ##################
DATABASE_URL: localhost
DATABASE_PASSWORD: 061201
DATABASE_USERNAME: postgres
DATABASE_NAME: OrderService
DATABASE_PORT: 5432